# Generated by Django 4.1.5 on 2023-02-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0002_gamesessionmoves_game_over_gamesessionmoves_winner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gamesessionmoves",
            old_name="move",
            new_name="position",
        ),
        migrations.RemoveField(
            model_name="gamesessionmoves",
            name="game_over",
        ),
        migrations.RemoveField(
            model_name="gamesessionmoves",
            name="winner",
        ),
        migrations.AddField(
            model_name="game",
            name="game_over",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="game",
            name="winner",
            field=models.CharField(
                blank=True, choices=[("X", "X"), ("O", "O")], max_length=1, null=True
            ),
        ),
    ]
