# Generated by Django 4.1.5 on 2023-02-27 08:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0003_rename_move_gamesessionmoves_position_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="gamesessionmoves",
            unique_together={("game", "position")},
        ),
    ]
